---
sudo: false
language: ruby
os:
  - linux
rvm:
  - 2.1.9
  - 2.2.10
  - 2.2.10-clang
  - 2.3.8
  - 2.3.8-clang
  - 2.4.9
  - 2.4.9-clang
  - 2.5.7
  - 2.6.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem install bundler
cache: bundler
